# Generated by Django 6.0.1 on 2026-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnshapeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_user_id', models.CharField(max_length=200, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('os_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('did', models.CharField(blank=True, max_length=200, null=True)),
                ('wv', models.CharField(blank=True, max_length=10, null=True)),
                ('wvid', models.CharField(blank=True, max_length=200, null=True)),
                ('eid', models.CharField(blank=True, max_length=200, null=True)),
                ('etype', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
