# Generated by Django 6.0.1 on 2026-01-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onshape_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onshapeuser',
            name='etype',
        ),
    ]
