# Generated by Django 6.0.1 on 2026-02-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onshape_app', '0002_remove_onshapeuser_etype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onshapeuser',
            old_name='wv',
            new_name='wvm',
        ),
    ]
