# Generated by Django 6.0.1 on 2026-02-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onshape_app', '0003_rename_wv_onshapeuser_wvm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onshapeuser',
            old_name='wvid',
            new_name='wvmid',
        ),
    ]
