# Generated by Django 6.0.1 on 2026-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshape_app', '0004_rename_wvid_onshapeuser_wvmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='onshapeuser',
            name='etype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
